### ISSUE TITLE
provider.cobblerx509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by zulkarnainsncr** [terraform-providers/terraform-provider-cobbler#10]
I am using a real certificate and now get the below error:
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* provider.cobbler: Post https://cobbler.vacum-np.sncrcorp.net/cobbler_web: x509: certificate signed by unknown authority

zkagalwallamac:cobbler zkag0001$ terraform -v
Terraform v0.11.2
+ provider.cobbler v1.0.0

Have a question is SSL supported for cobbler provider?

**Comment by jtopjian** [comment]
Unfortunately self-signed certificates are not supported at this time. I'm going to close this in favor of #7 which can be used to track this. Please let me know if you have any questions, though.

**Comment by zulkarnainsncr** [comment]
We are not using self signed certificate.

**Comment by jtopjian** [comment]
> x509: certificate signed by unknown authority

This might be a general Go/SSL issue, then. There might be an option required in this provider to specify an intermediate CA.
