### ISSUE TITLE
Suggestion, cobbler system should be recreated if it is not found

### ISSUE THREAD

**Issue by toddnni** [terraform-providers/terraform-provider-cobbler#13]
### Terraform Version
Terraform v0.11.3

### Affected Resource(s)
- cobbler_system

(Note, I didn't check but the same behavior might be in all the resources in this provider)

### Steps to Reproduce

1. Define cobbler system in config
2. run `terraform apply`
3. Delete the system in cobbler `cobbler system remove --name XXX`
4.  run `terraform apply`

### Actual Behavior
The provider will print out an error message like this 
```
cobbler_system.pxesetup: Refreshing state... (ID: ns.example.com)

Error: Error refreshing state: 1 error(s) occurred:

* module.master.cobbler_system.pxesetup: 1 error(s) occurred:

* module.master.cobbler_system.pxesetup: cobbler_system.pxesetup: Cobbler System: Error Reading (ns.example.com): System ns.example.com not found.
```

### Expected Behavior
I expect similar behavior as in some other terraform providers that resource will converge automatically. It other words, if system is not found it will be recreated. With current code I need to clean terraform state to trigger the recreation. However, we should differentiate error case "could not connect to cobbler API" from error "system not found", and make it only recreate the resource in "system not found" case.

Use case is to manage the list of systems  even if the cobbler host is recreated on fly.

### How to fix
I'm interested to help if the fix is easy, but it seems that it might involve the interface between cobblerclient and the provider.

In cobblerclient the "system not found" error is thrown here
https://github.com/jtopjian/cobblerclient/blob/33eb2ad02f4f784ee66b5eb2e1a0c00c56d7a86e/system.go#L144

And it is catched here 
https://github.com/terraform-providers/terraform-provider-cobbler/blob/192f88731620a5dde47c67ea34f05782fb3007a7/cobbler/resource_cobbler_system.go#L465

The only ideas I have
a. List all the systems and check if the system is actually in the list
b. Modify error handling in cobblerclient somehow to signal that host is not found

**Comment by bflad** [comment]
Hi @toddnni! 👋  Thanks for the report here! It turns out its pretty easy for us to trigger Terraform to recreate a resource when its missing on read. Here's an example of how we do it in the AWS provider:

```go
// try reading
if err != nil {
  if isAWSErr(err, dynamodb.ErrCodeResourceNotFoundException, "") {
    log.Printf("[WARN] Dynamodb Table (%s) not found, error code (404)", d.Id())
    d.SetId("")
    return nil
  }
  return err
}
```

In this case, you can probably implement similar logic, (please note: I'm not too familiar with the cobbler provider itself, so there might be a better or more correct way), e.g.

```go
// try reading
if err != nil {
  if strings.Contains(err, "not found") {
    log.Printf("[WARN] Cobbler System (%s) not found, removing from state", d.Id())
    d.SetId("")
    return nil
  }
  return fmt.Errorf("Cobbler System: Error Reading (%s): %s", d.Id(), err)
}
```

Hope this helps!

**Comment by jtopjian** [comment]
Yep, that sounds about right. I can get this added to the provider when I have a moment.

**Comment by jtopjian** [comment]
@toddnni #14 will fix this.

@bflad Thank you for the suggestion. It was spot-on.

**Comment by toddnni** [comment]
Thank you both for the fix.
