### ISSUE TITLE
Please correct the doc for cobbler profile resource 

### ISSUE THREAD

**Issue by etc-fstab** [terraform-providers/terraform-provider-cobbler#17]
The URL to review: https://www.terraform.io/docs/providers/cobbler/r/profile.html

I believe there is error here, it reads:

resource "cobbler_profile" "my_profile" {
  name   = "/var/lib/cobbler/snippets/my_snippet" <--- ERROR
  distro = "ubuntu-1404-x86_64"
}

You probably want something like:

resource "cobbler_profile" "OL-R7-U5-x86_64_attended" {
  name   = "OL-R7-U5-x86_64_attended"
  distro = "OL-R7-U5-x86_64"
  kickstart = "/var/lib/cobbler/kickstarts/default.ks"
}

**Comment by jtopjian** [comment]
@zdudic Good catch - thank you. This has been fixed in #18
