### ISSUE TITLE
Provide support for Cobbler 3.x

### ISSUE THREAD

**Issue by hbokh** [terraform-providers/terraform-provider-cobbler#31]
Hello,

Please provide support for [Cobbler 3.x](https://github.com/cobbler/cobbler).
Terrafrom v0.12.19 and provider.cobbler v1.1.0 are not compatible with the latest incarnations of Cobbler version 3.x.
Cc @jtopjian 

### Terraform Version
```
Terraform v0.12.19
+ provider.cobbler v1.1.0
```

### Affected Resource(s)
- cobbler

### Terraform Configuration Files
```hcl
resource "cobbler_system" "cobbler0-dev" {
  count           = "1"
  name            = "cobbler0-dev"
  profile         = "debian10-x86_64"
  hostname        = "cobbler0-dev.example.com"
  kickstart       = "/var/lib/cobbler/kickstarts/debian10.seed"
  kernel_options  = "netcfg/choose_interface=ens18"
  ks_meta         = "fs=ext4 swap=1024 env=dev"
  status          = "development"
  netboot_enabled = "1"

  #Backend VLAN #######################
  interface {
    name          = "ens18"
    mac_address   = "AE:C7:8F:F9:13:95"
    ip_address    = "10.10.11.139"
    netmask       = "255.255.255.0"
    dhcp_tag      = "grqtst"
    dns_name      = "cobbler0-dev.example.lan"
    static_routes = ["10.10.11.0/24:10.10.11.1"]
    static        = true
    management    = true
  }

  # Public ################################
  interface {
    name        = "ens19"
    mac_address = "F6:87:24:DC:F9:31"
    ip_address  = "127.35.11.139"
    netmask     = "255.255.255.128"
    gateway     = "127.35.11.129"
    dns_name    = "cobbler0-dev.example.com"
    static      = true
  }
}
```

### Debug Output

I can probably best add this later on (if needed), since the current issue is caused by incompatibilities in `terraform-provider-cobbler` and [jtopjian/cobblerclient](https://github.com/jtopjian/cobblerclient) against code rewrites in the API of Cobbler 3.x. 

### Panic Output
No panic output

### Expected Behavior
A new system from `main.tf` added to Cobbler 3.1.1 (latest Terraform plus this provider & the HCL above are OK when applied against Cobbler 2.6.11).

### Actual Behavior

For `cobbler_system`:
```
cobbler_system.cobbler0-dev[0]: Creating...

Error: Cobbler System: Error Creating: Error updating kickstart to debian10.seed.

  on main.tf line 1, in resource "cobbler_system" "cobbler0-dev":
   1: resource "cobbler_system" "cobbler0-dev" {
```

For `cobbler_kickstart_file`:
```
Error: Cobbler KickstartFile: Error Creating: error: "<class 'cobbler.cexceptions.CX'>:"unknown remote method 'read_or_write_kickstart_template'"" code: 1
```

### Steps to Reproduce

1. Install and setup Cobbler 3.1.x in Virtualbox `bento/fedora-31` - pre-build binaries can be found for Fedora 31 
2. Setup a Terraform env with the Cobbler Provider
3. `terraform apply`

### Important Factoids
Over the last months there is actively being worked on Cobbler 3.x.
IMO it's a matter of time before the older 2.6 and 2.8 version are being called obsolete / EOL.

Terms like `kickstarts` have been replaced with `templates`.

### References

- "Python2 is EOL and 2.8.x will most definitely die" https://github.com/cobbler/cobbler/issues/2239#issuecomment-575134683
- "XMLRPC responses changed in 3.x" https://github.com/cobbler/cobbler/issues/2030
- https://github.com/cobbler/cobbler/issues/2238#issuecomment-575627850

**Comment by jtopjian** [comment]
@hbokh Unfortunately I'm not longer working on this provider, though I'm happy to assist others where I can with any questions or reviews.

**Comment by hbokh** [comment]
Thanks @jtopjian. In the meantime I'll add some info and changes I discovered along the way. If I was a hacker I could try and change the code myself but my previous PR here didn't work out...

The [Cobbler-XMLRPC-API](https://github.com/cobbler/cobbler/wiki/Cobbler-XMLRPC-API) has not been rewritten for v3 (yet), so I started looking into the source instead and did some XMLRPC experiments against v2.x and v3.1.1 myself.

This specific provider depends on the repo `jtopjian/cobblerclient`. That repo needs to be updated or forked with code changes.
In Cobbler 3  the `read_or_write_kickstart_template` was replaced with new options:

- `read_autoinstall_template`
- `write_autoinstall_template`
- `remove_autoinstall_template`

See https://github.com/cobbler/cobbler/blob/master/cobbler/remote.py#L2103 (v3) compared to https://github.com/cobbler/cobbler/blob/release28/cobbler/remote.py#L1919 (v2).

That means these lines https://github.com/jtopjian/cobblerclient/blob/master/kickstart_file.go#L19-L56 need to be rewritten for the kickstart (now named "templates").

The same goes for `read_or_write_snippet` in `snippet.go` (etc.) and probably even more.

**Comment by hbokh** [comment]
Created a fork and feature branch of `jtopjian/cobblerclient` under my employer's account: https://github.com/wearespindle/cobblerclient/

Unaware of Go-programmers tricks, there's not much more I can do, I guess...
~Oh and I couldn't get around this one~ `undefined: xmlrpc.NewResponse`

**Comment by jtopjian** [comment]
Nice work looking into this.

It appears that there are hard incompatibilities between the v2 and v3 XMLRPC API. 

You're correct in that this provider is built around the `cobblerclient` go library I wrote and so that core library needs updated. Since v2 and v3 are incompatible, either:

1. The library needs forked and a separate v3-compatible library needs to be maintained or
2. v3 support is added to the existing library by way of creating new functions like `CreateTemplate`, `GetTemplate`, etc. In cases where existing functions overlap new functions, new functions would be added such as `CreateFooV3` and the existing `CreateFoo` would be left for v2 support.

Once that's done, similar behavior would need to be done with this provider:

1. The provider is updated for v3 support and v2 support is dropped
2. A new v3 provider is created
3. Additional v3-only resources are added alongside the existing v2 (base/default) resources.

**Comment by hbokh** [comment]
I have been working on both the `cobblerclient` and `terraform-provider-cobbler` over the last weeks and have reached the point where  things are working in multiple ways with Cobbler 3.
Adding a system based on a profile was the most important one for me.
Being the "glue developer" I am (so without any programming background), I have reached the point where I am unable to make it from "**working somehow**" / "good enough" to "perfect".
It was great fun though, puzzling with the new and old options, but I don't think a PR is the right thing to do ATM.

Anyway, the code is in these repos:

- https://github.com/wearespindle/cobblerclient
- https://github.com/wearespindle/terraform-provider-cobbler

There is no backwards compatibility with Cobbler 2, that is way beyond what I'm capable of.
Unsure if that is even wanted in the long run, since Cobbler 2 is Python2 based and [sic] "will most definitely die".

So I have reached the point where I ask help from the community to improve on the basic base I have laid. Maybe HashiCorp's @radeksimko can be of any help here. 😇

Testing has been done with Cobbler 3.1.1 on both Debian and Fedora 31.
For Cobbler 3 testing I suggest using a Vagrant virtualbox with Fedora 31 eg. `bento/fedora-31`, since there are ready build RPMs available (just use `dnf install cobbler cobbler-web` and you're halfway there).

- [cobbler](https://fedora.pkgs.org/31/fedora-updates-x86_64/cobbler-3.1.1-1.fc31.noarch.rpm.html)
- [cobbler-web](https://fedora.pkgs.org/31/fedora-updates-x86_64/cobbler-web-3.1.1-1.fc31.noarch.rpm.html)

**Comment by jtopjian** [comment]
@hbokh Nice work 😄 

I will try to get some time over the next few days to take a look at this.

> There is no backwards compatibility with Cobbler 2, that is way beyond what I'm capable of.
> Unsure if that is even wanted in the long run, since Cobbler 2 is Python2

This makes sense.

One possible option would be for your Cobbler 3 work to supersede all previous work. Prior releases of the library and provider can be used for Cobbler 2 interaction, but any new releases will be for Cobbler 3 only.

**Comment by hbokh** [comment]
Some new perspective: https://github.com/cobbler/cobbler/issues/2248#issuecomment-584294821

**Comment by jtopjian** [comment]
@hbokh I apologize - I haven't been able to look into this. Out of curiosity, have you updated the acceptance test suite for your changes and have gotten them to pass? If not, that would be the next area to look at - having a passing acceptance test suite would confirm functionality.

Let me know if you have problems getting the test to run.

**Comment by hbokh** [comment]
> @hbokh I apologize - I haven't been able to look into this. Out of curiosity, have you updated the acceptance test suite for your changes and have gotten them to pass? If not, that would be the next area to look at - having a passing acceptance test suite would confirm functionality.
> 
> Let me know if you have problems getting the test to run.

Hi @jtopjian and thanks for the response, Joe.
I think you mean the test in `terraform-provider-cobbler/cobbler/acceptance_env`?
Because the answer is no, unfortunately. I'd like to setup a test in which AWS is not a prerequisite.

So far we have been testing "live" against Cobbler 3.1.x  running in a Vagrantbox (`bento/debian-10.2`).

If you meant the other test,  the `make test` for the `cobblerclient` needs to have some TLC too: 

```
# make test                                                                                                                                            
=== RUN   TestLogin
--- PASS: TestLogin (0.00s)
=== RUN   TestLoginWithError
--- PASS: TestLoginWithError (0.00s)
=== RUN   TestGetDistros
--- FAIL: TestGetDistros (0.00s)
    testing.go:7: 5 error(s) decoding:

        * 'boot_files' expected type 'string', got unconvertible type 'map[string]interface {}'
        * 'fetchable_files' expected type 'string', got unconvertible type 'map[string]interface {}'
        * 'kernel_options' expected type 'string', got unconvertible type 'map[string]interface {}'
        * 'kernel_options_post' expected type 'string', got unconvertible type 'map[string]interface {}'
        * 'template_files' expected type 'string', got unconvertible type 'map[string]interface {}'
=== RUN   TestGetDistro
--- PASS: TestGetDistro (0.00s)

--- cut ---
```

**Comment by jtopjian** [comment]
> Because the answer is no, unfortunately. I'd like to setup a test in which AWS is not a prerequisite.

This is definitely possible to do. AWS is bundled because that's what HashiCorp's internal test system launches instances on. If you're able to modify/update https://github.com/terraform-providers/terraform-provider-cobbler/blob/master/cobbler/acceptance_env/deploy.sh so that the instructions are good for any kind of Linux virtual machine (AWS, VagrantBox, etc), that would go a long way to assist with reproducibility and verification.

> If you meant the other test, the make test for the cobblerclient needs to have some TLC too:

Let me know if you get stumped on these and I'll see if I can find some time to help. I apologize for not being available - I've been tied up with a bunch of other things lately.

**Comment by hbokh** [comment]
Some updates on the tests. Still testing locally in VirtualBox & Vagrant. Will ~try to~ provide a Vagrantfile with provisioning ~some time later~ below.

The `make test` for `cobblerclient` looks OK now:
- PR https://github.com/wearespindle/cobblerclient/pull/7

The `make testacc` for the provider is fighting with Cobbler 3.1.1:
- PR https://github.com/wearespindle/terraform-provider-cobbler/pull/6

```txt
=== RUN   TestAccCobblerProfile_basic
--- FAIL: TestAccCobblerProfile_basic (0.21s)
    testing.go:629: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: Cobbler Distro: Error Deleting (foo): Fault(1): <class 'TypeError'>:'<' not supported between instances of 'str' and 'NoneType'

--- cut ---
```

**Comment by hbokh** [comment]
Testing manually with Terraform CLI and apply / edit / destroy `Distro foo`.
That works OK. I'm puzzled.

```console
$ terraform apply -auto-approve
cobbler_distro.foo: Creating...
cobbler_distro.foo: Creation complete after 0s [id=foo]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

$ vi main.tf # Adding comment

$ terraform apply -auto-approve
cobbler_distro.foo: Refreshing state... [id=foo]
cobbler_distro.foo: Modifying... [id=foo]
cobbler_distro.foo: Modifications complete after 0s [id=foo]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

$ vi main.tf # Editing comment

$ terraform apply -auto-approve
cobbler_distro.foo: Refreshing state... [id=foo]
cobbler_distro.foo: Modifying... [id=foo]
cobbler_distro.foo: Modifications complete after 0s [id=foo]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

$ terraform destroy -auto-approve
cobbler_distro.foo: Refreshing state... [id=foo]
cobbler_distro.foo: Destroying... [id=foo]
cobbler_distro.foo: Destruction complete after 0s

Destroy complete! Resources: 1 destroyed.
```

```console
$ cat main.tf
resource "cobbler_distro" "foo" {
  name        = "foo"
  comment     = "I am a distro again"
  breed       = "ubuntu"
  os_version  = "bionic"
  arch        = "x86_64"
  boot_loader = "grub"
  kernel      = "/var/www/cobbler/distro_mirror/Ubuntu-18.04/install/netboot/ubuntu-installer/amd64/linux"
  initrd      = "/var/www/cobbler/distro_mirror/Ubuntu-18.04/install/netboot/ubuntu-installer/amd64/initrd.gz"
}
```

**Comment by hbokh** [comment]
Here's a gist to provide both a `Vagrantfile` and `deploy.sh`:
https://gist.github.com/hbokh/4ca0838e9b8154a29c13bff7a7c7dba2

Needs some more work to apply patches not in the 3.1.1 release.
- ~disable caching that was introduced in Cobbler 3.0.x~ (patch `item.py`) ✅
- ~fix snippet delete~ (fetch `autoinstall_manager.py`) ✅

**Comment by hbokh** [comment]
Running the other test `cobblerclient/cmd` (pointing to the VagrantBox, URL set to `http://cobbler.internal/cobbler_api`, compiled with `go build`) is showing the issue with the distro in an early state.

```console
$ ./cmd
Token: 0xk35N5ZSSWzViyYT75PZjmD0dB7C/e7wA==
Creating a repo
&{Ctime:1.582541111711521e+09 Depth:2 ID:645fb207e3b4443cbff9220ffe775748 Mtime:1.582541111711521e+09 TreeBuildTime: AptComponents:[] AptDists:[] Arch:x86_64 Breed:yum Comment: CreateRepoFlags: Environment:[] KeepUpdated:false Mirror:http://repo/homeawayel7/ MirrorLocally:false Name:myrepo Owners:[] Proxy: RpmList:[]}
Listing all repos
&{Ctime:1.5825336495274951e+09 Depth:2 ID:7873f81974ff4e9aa9d84fe171c9ea13 Mtime:1.5825389996811926e+09 TreeBuildTime: AptComponents:[main] AptDists:[bionic] Arch:x86_64 Breed:apt Comment: CreateRepoFlags:<<inherit>> Environment:[] KeepUpdated:false Mirror:http://nl.archive.ubuntu.com/ubuntu/ MirrorLocally:false Name:Ubuntu-18.04-x86_64 Owners:[admin] Proxy:<<inherit>> RpmList:[]}
&{Ctime:1.582541111711521e+09 Depth:2 ID:645fb207e3b4443cbff9220ffe775748 Mtime:1.582541111711521e+09 TreeBuildTime: AptComponents:[] AptDists:[] Arch:x86_64 Breed:yum Comment: CreateRepoFlags: Environment:[] KeepUpdated:false Mirror:http://repo/homeawayel7/ MirrorLocally:false Name:myrepo Owners:[] Proxy: RpmList:[]}
Deleting a repo
Creating a Distro
New Distro: &{Ctime:1.5825411117461996e+09 Depth:0 ID:e96f426ebc3c44259a86a1ca15b06e97 Mtime:1.5825411117461996e+09 TreeBuildTime: Arch:x86_64 Breed:ubuntu BootFiles: BootLoader:grub Comment: FetchableFiles: Kernel:/var/www/cobbler/distro_mirror/Ubuntu-18.04/install/netboot/ubuntu-installer/amd64/linux KernelOptions: KernelOptionsPost: Initrd:/var/www/cobbler/distro_mirror/Ubuntu-18.04/install/netboot/ubuntu-installer/amd64/initrd.gz MGMTClasses:[] Name:Test OSVersion:bionic Owners:[] TemplateFiles:}
Updating Distro
Creating a Profile
New Profile: &{Ctime:1.5825411121057124e+09 Depth:1 ID:63d67a78d70545ad8a7a42351e872ada Mtime:1.5825411121057124e+09 ReposEnabled:false Autoinstall:sample.seed AutoinstallMeta: BootFiles: Comment: DHCPTag: Distro:Test EnableGPXE:false EnableMenu:false FetchableFiles: KernelOptions: KernelOptionsPost: MGMTClasses:[] MGMTParameters:<<inherit>> Name:Testy NameServers:[] NameServersSearch:[] NextServer:<<inherit>> Owners:[] Proxy: Repos: Server:<<inherit>> TemplateFiles: VirtAutoBoot:0 VirtBridge:xenbr0 VirtCPUs:1 VirtDiskDriver:<<inherit>> VirtFileSize:0 VirtPath: VirtRAM:<<inherit>> VirtType:<<inherit>> Client:{httpClient:0x17ba260 config:{URL:http://cobbler.internal/cobbler_api Username:cobbler Password:cobbler} Token:0xk35N5ZSSWzViyYT75PZjmD0dB7C/e7wA==}}
Creating a System
New System: &{Ctime:1.5825411121685944e+09 Depth:2 ID:ffd3ebe026034545b3312144d487f76c IPv6Autoconfiguration:false Mtime:1.5825411121685944e+09 ReposEnabled:false Autoinstall: AutoinstallMeta: BootFiles: BootLoader:<<inherit>> Comment:WTF EnableGPXE:false FetchableFiles: Gateway: Hostname: Image: Interfaces:map[] IPv6DefaultDevice: KernelOptions: KernelOptionsPost: MGMTClasses:[] MGMTParameters:<<inherit>> Name:Foobar NameServers:[8.8.8.8 1.1.1.1] NameServersSearch:[] NetbootEnabled:false NextServer:<<inherit>> Owners:[] PowerAddress: PowerID:foo PowerPass: PowerType:ipmilan PowerUser: Profile:Testy Proxy:<<inherit>> Status:production TemplateFiles: VirtAutoBoot:0 VirtCPUs:<<inherit>> VirtDiskDriver:<<inherit>> VirtFileSize:<<inherit>> VirtPath:<<inherit>> VirtPXEBoot:0 VirtRAM:<<inherit>> VirtType:<<inherit>> Client:{httpClient:0x17ba260 config:{URL:http://cobbler.internal/cobbler_api Username:cobbler Password:cobbler} Token:0xk35N5ZSSWzViyYT75PZjmD0dB7C/e7wA==}}
Adding NIC to System
Adding second NIC to System
Syncing the cobbler server
Getting system
Verifying NIC data
map[eth0:{CNAMEs:[] DHCPTag: DNSName: BondingOpts: BridgeOpts: Gateway: InterfaceType:bridge InterfaceMaster: IPAddress: IPv6Address: IPv6Secondaries:[] IPv6MTU: IPv6StaticRoutes:[] IPv6DefaultGateway: MACAddress:aa:bb:cc:dd:ee:ff Management:false Netmask: Static:true StaticRoutes:[] VirtBridge:xenbr0} eth1:{CNAMEs:[] DHCPTag: DNSName: BondingOpts: BridgeOpts: Gateway: InterfaceType: InterfaceMaster: IPAddress: IPv6Address: IPv6Secondaries:[] IPv6MTU: IPv6StaticRoutes:[] IPv6DefaultGateway: MACAddress:aa:bb:cc:dd:ee:fa Management:true Netmask: Static:true StaticRoutes:[] VirtBridge:xenbr0}]

eth0:
{CNAMEs:[] DHCPTag: DNSName: BondingOpts: BridgeOpts: Gateway: InterfaceType:bridge InterfaceMaster: IPAddress: IPv6Address: IPv6Secondaries:[] IPv6MTU: IPv6StaticRoutes:[] IPv6DefaultGateway: MACAddress:aa:bb:cc:dd:ee:ff Management:false Netmask: Static:true StaticRoutes:[] VirtBridge:xenbr0}

eth1:
{CNAMEs:[] DHCPTag: DNSName: BondingOpts: BridgeOpts: Gateway: InterfaceType: InterfaceMaster: IPAddress: IPv6Address: IPv6Secondaries:[] IPv6MTU: IPv6StaticRoutes:[] IPv6DefaultGateway: MACAddress:aa:bb:cc:dd:ee:fa Management:true Netmask: Static:true StaticRoutes:[] VirtBridge:xenbr0}

Deleting Interface
Deleting System
Deleting Profile
Deleting Distro
Error deleting distro: Fault(1): <class 'TypeError'>:'<' not supported between instances of 'str' and 'NoneType'
Creating a Snippet
Deleting a Snippet
Creating a Template
Deleting a Template
```

**Comment by hbokh** [comment]
> Error deleting distro: Fault(1): <class 'TypeError'>:'<' not supported between instances of 'str' and 'NoneType'

Probably another caching issue that was introduced sometime after 2.8.x. (Ref. https://github.com/cobbler/cobbler/pull/1807)
The created distro "Test" can not be **modified** (saved) in the webUI either (it can be be deleted!), but it can once you **restart** the cobbler daemon.

**Comment by hbokh** [comment]
@jtopjian The added caching in the Cobbler 3.x branch seems to become a blocking issue.

To compare with the 2.8.x branch, I've run `cobblerclient/cmd` with some small modifications for XMLRPC against Cobbler 2.8.5 on CentOS7 without major issue.
Minor issue was this error:

```
1 error(s) decoding:

* 'environment' expected type 'string', got unconvertible type 'map[string]interface {}'
```

but the distro was deleted with no problem.

**Diffs**

```diff
diff --git a/cobblerclient.go b/cobblerclient.go
index 76c5c76..b06bbd4 100644
--- a/cobblerclient.go
+++ b/cobblerclient.go
@@ -74,13 +74,13 @@ func (c *Client) Call(method string, args ...interface{}) (interface{}, error) {
                return nil, err
        }

-       resp := xmlrpc.NewResponse(body)
+       resp := xmlrpc.Response(body)
        if err := resp.Unmarshal(&result); err != nil {
                return nil, err
        }

-       if resp.Failed() {
-               return nil, resp.Err()
+       if err := resp.Err(); err != nil {
+               return nil, err
        }

        return result, nil

diff --git a/repo.go b/repo.go
index a9fa019..6d669f3 100644
--- a/repo.go
+++ b/repo.go
@@ -36,7 +36,7 @@ type Repo struct {
        Breed           string   `mapstructure:"breed"`
        Comment         string   `mapstructure:"comment"`
        CreateRepoFlags string   `mapstructure:"createrepo_flags"`
-       Environment     string   `mapstructure:"environment"`
+       Environment     []string `mapstructure:"environment"`
        KeepUpdated     bool     `mapstructure:"keep_updated"`
        Mirror          string   `mapstructure:"mirror"`
        MirrorLocally   bool     `mapstructure:"mirror_locally"`
```

**Comment by jtopjian** [comment]
> The created distro "Test" can not be modified (saved) in the webUI either (it can be be deleted!), but it can once you restart the cobbler daemon.
>
> The added caching in the Cobbler 3.x branch seems to become a blocking issue.

From looking at the PR you linked to, there doesn't seem to be a way to opt-out of caching? I'd consider this to be a bug in Cobbler, especially if you can reproduce the issue in the native Cobbler Web UI. In this case, I'd say Cobbler 3.x possibly isn't stable yet?

> Minor issue was this error:

I ran into this _a lot_ when I first started working on cobblerclient. The main reason is when the _request_ type is different than the _response_ type. The best long-term solution for this is for `cobblerclient` to have two types of structs: one for request and one for response. It would be a big refactor and something I didn't have time to work on. I was able to get by hacking around the issue.

**Comment by hbokh** [comment]
Well, I did another deep dive into the Cobbler Python code and had to hack Cobbler`cobbler/items/item.py` once more by changing `sorted=True` to `sorted=False`:
https://github.com/cobbler/cobbler/blob/master/cobbler/items/item.py#L235

**Once more**, because this line has to be uncommented too:
https://github.com/cobbler/cobbler/blob/master/cobbler/items/item.py#L218
Leaving that specific line commented, will result in this error while using Terraform Cobbler Provider:

`Error: Cobbler Profile: Error Creating: Fault(1): <class 'AttributeError'>:'str' object has no attribute 'copy'`

Made some small modifications in the `TestAccCobblerSystem_multi` loop, but final result is **PASS**. 🎉

```
$ make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?   	github.com/wearespindle/terraform-provider-cobbler	[no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccCobblerDistro_basic
--- PASS: TestAccCobblerDistro_basic (0.27s)
=== RUN   TestAccCobblerDistro_change
--- PASS: TestAccCobblerDistro_change (0.36s)
=== RUN   TestAccCobblerProfile_basic
--- PASS: TestAccCobblerProfile_basic (0.20s)
=== RUN   TestAccCobblerProfile_change
--- PASS: TestAccCobblerProfile_change (0.54s)
=== RUN   TestAccCobblerProfile_withRepo
--- PASS: TestAccCobblerProfile_withRepo (0.20s)
=== RUN   TestAccCobblerRepo_basic
--- PASS: TestAccCobblerRepo_basic (0.10s)
=== RUN   TestAccCobblerRepo_change
--- PASS: TestAccCobblerRepo_change (0.18s)
=== RUN   TestAccCobblerSnippet_basic
--- PASS: TestAccCobblerSnippet_basic (0.06s)
=== RUN   TestAccCobblerSystem_basic
--- PASS: TestAccCobblerSystem_basic (0.49s)
=== RUN   TestAccCobblerSystem_multi
--- PASS: TestAccCobblerSystem_multi (29.90s)
=== RUN   TestAccCobblerSystem_change
--- PASS: TestAccCobblerSystem_change (1.06s)
=== RUN   TestAccCobblerSystem_removeInterface
--- PASS: TestAccCobblerSystem_removeInterface (1.18s)
=== RUN   TestAccCobblerTemplateFile_basic
--- PASS: TestAccCobblerTemplateFile_basic (0.08s)
PASS
ok  	github.com/wearespindle/terraform-provider-cobbler/cobbler	34.638s
```

The other test `cobblerclient/cmd` is now also "Deleting Distro".

**Comment by holmesb** [comment]
Is there much left to do now the tests are passing to raise a PR and get this merged?  Cobbler 3 has been out for a year and there have been many releases & bug-fixes since.  Backward-incompatibility with Cobbler 2 shouldn't be a blocker IMO.

**Comment by hbokh** [comment]
@holmesb Since it seems the support for this specific Terraform provider has stopped, we have released our own version of the Cobbler provider that supports Cobbler 3 **only**:
- https://github.com/wearespindle/terraform-provider-cobbler

It depends on an updated `cobblerclient`:
- https://github.com/wearespindle/cobblerclient

Also Cobbler 3 added some breaking changes, for example due to added caching (https://github.com/cobbler/cobbler/pull/1807). We patched Cobbler 3 to make sure it works with our Terraform configuration.
I covered the changes we made in our "patched version" of Cobbler 3.1.x here: https://github.com/cobbler/cobbler/pull/2283#issuecomment-598271114

**Comment by holmesb** [comment]
Hi @hbokh, great work getting bringing this provider up to date.  Your [comment](https://github.com/cobbler/cobbler/pull/2283#issuecomment-598271114) says this line should be commented:
https://github.com/cobbler/cobbler/blob/master/cobbler/items/item.py#L218
Currently this line is: `Must be defined in any subclass` which might be wrong because this link is to the dynamic master branch. 
 Pls could you post a permalink to the correct line instead.  You can do that by clicking the space on the left of the line-number, the three dots, then choose "Copy permalink".

There is only one `sorted=True` so I assume [this ](https://github.com/cobbler/cobbler/blob/172b8a0f79d110dcac1f50acfe412e0a01ff20ab/cobbler/items/item.py#L282)is right.

**Comment by hbokh** [comment]
Oh yes, you're right! Copying lines from "master"... 🤪
 
> There is only one `sorted=True` so I assume [this ](https://github.com/cobbler/cobbler/blob/172b8a0f79d110dcac1f50acfe412e0a01ff20ab/cobbler/items/item.py#L282)is right.

This block indeed, to what was once around L235:

```python
     def get_children(self, sorted=False):  # <== set to "False", so we can actually sort!
         """
         Get direct children of this object.
         """
```

And here the uncommented line that used to be L218

```python
     def to_dict(self):
         return utils.to_dict_from_fields(self, self.get_fields())  # <== UNCOMMENTED LINE

         value = self.get_from_cache(self)
         if value is None:
             value = utils.to_dict_from_fields(self, self.get_fields())
         self.set_cache(self, value)
         return value
```

HTH!

**Comment by jtopjian** [comment]
> Since it seems the support for this specific Terraform provider has stopped,

I wouldn't say that support has stopped. I think support for Cobbler 3.x would be welcomed, even if it was a breaking change or caused a new major version of this provider to be released.

I think the main issue is that changes to the Cobbler service itself are required to make this provider work. IMO, that points to bugs in Cobbler - if a tool cannot communicate with Cobbler via the API then the API is broke, no? 

Since I no longer work on this provider, I don't have any insight into internal discussion or policies, but my assumption would be that it's preferable to have a stable, known-working release of an older version than releasing a new version that requires modifications to be made to the service in order for it to work.

**Comment by lazzurs** [comment]
@hbokh with the change in Terraform to move providers to the registry do you intend to maintain this provider in the future?

I ask because I had starting to look at moving this provider over but it seems like you have been doing great work with the provider and the future should be with your fork.

**Comment by hbokh** [comment]
> with the change in Terraform to move providers to the registry do you intend to maintain this provider in the future?

No, sorry.
With the "provider for a patched Cobbler v3" this would be hard. Besides I lack skills in Go.

@jtopjian Good reply, thanks Joe!
My "support seems stopped" is mainly driven by the fact that there is a good looking PR #30 waiting for over 7 months with no action taken so far. That made me get the impression.

**Comment by jtopjian** [comment]
> My "support seems stopped" is mainly driven by the fact that there is a good looking PR #30 waiting for over 7 months with no action taken so far. That made me get the impression.

Extremely valid point! There's also a small PR that can also be merged. Let me see if I can contact someone to see what the status of this provider is.

**Comment by holmesb** [comment]
The Cobbler XMLRPC api is broken since caching was enabled in Cobbler v3.0.0.  I've opened [an issue ](https://github.com/cobbler/cobbler/issues/2386)in that project which demonstrates native XMLRPC API calls fail and [a PR](https://github.com/cobbler/cobbler/pull/2387) to fix.

**Comment by jtopjian** [comment]
@holmesb's comment notification reminded me that I did try contacting someone about getting the open PRs merged and asking about the general state of this provider. Unfortunately I did not hear back.

**Comment by holmesb** [comment]
For reference, I added an option to Cobbler that disables caching since it breaks remote XMLRPC calls (and terraform).  Cobbler is currently v3.1.2.  After the next release, add:
`cache_enabled: 0`
to /etc/cobbler/settings
(default is 1)
I expect @hbokh can then raise a PR (including documentation for this setting) and it will be good to merge.

**Comment by holmesb** [comment]
Hi @hbokh, [the new Cobbler v3.2.0 release](https://github.com/cobbler/cobbler/releases/tag/v3.2.0) contains my fix to disable cache.  Are you able to raise a PR?

**Comment by hbokh** [comment]
> Hi @hbokh, [the new Cobbler v3.2.0 release](https://github.com/cobbler/cobbler/releases/tag/v3.2.0) contains my fix to disable cache. Are you able to raise a PR?

Hi @holmesb,

Just to be sure, from the `wearespindle/terraform-provider-cobbler` repo?
https://github.com/wearespindle/terraform-provider-cobbler

**Comment by holmesb** [comment]
Yes that's where you pushed your fixes for Cobbler v3.x.  Do you have an alternative in mind?

**Comment by hbokh** [comment]
> Yes that's where you pushed your fixes for Cobbler v3.x. Do you have an alternative in mind?

No. Have to finish my ☕ before posting...
PR on its way!

**Comment by hbokh** [comment]
PR #32 
Possibly the [`cobblerclient`](https://github.com/wearespindle/cobblerclient) needs to be dealt with in @jtopjian 's repo.

**Comment by hbokh** [comment]
Closed. I am nearing the point of publishing a community plugin under the Cobbler organization.
