### ISSUE TITLE
cobbler provider fail to run any resource if server presents self-signed certificate

### ISSUE THREAD

**Issue by mploski** [terraform-providers/terraform-provider-cobbler#7]
### Terraform Version
Terraform v0.10.0

### Affected Resource(s)
all resources which needs to connect to cobbler

### Terraform Configuration Files
```hcl
provider "cobbler" {
  username = "${var.cobbler_username}"
  password = "${var.cobbler_password}"
  url      = "${var.cobbler_url}"
}

terraform {
  backend "s3" {
    bucket = "sdwan-terraform-state"
    key    = "beast/terraform.tfstate"
    region = "us-east-2"
  }
}


variable "cobbler_username" {
  description = "Cobbler username"
  type = "string"
  default = "xxx"
}

variable "cobbler_password" {
  description = "Run the EC2 Instances in these Availability Zones"
  type = "string"
}

variable "cobbler_url" {
  description = ""
  type = "string"
  default = "https://10.32.5.100/cobbler_web"
}

resource "cobbler_distro" "beast_distro" {
  name       = "ubuntu-16.04.2-server-x86_64"
  owners      = ["admin"]
  breed      = "ubuntu"
  os_version = "xenial"
  arch       = "x86_64"
  kernel     = "/var/www/cobbler/ks_mirror/ubuntu-16.04.2-server-amd64-x86_64/install/netboot/ubuntu-installer/amd64/linux"
  initrd     = "/var/www/cobbler/ks_mirror/ubuntu-16.04.2-server-amd64-x86_64/install/netboot/ubuntu-installer/amd64/initrd.gz"
}

resource "cobbler_kickstart_file" "beast_base_os_kickstart" {
  name = "/var/lib/cobbler/kickstarts/my_kickstart.ks"
  body = "${file("beast_base_os_kickstart.seed")}"
}

```
### Debug Output
https://gist.github.com/mludy/a3febf29e6062f8bad3adb66f300f238#file-gistfile1-txt

### Expected Behavior
Module should have options to accept self-signed cobbler server certificate

### Actual Behavior
Request to cobbler is interrupted because of not trusted server certificate

### Steps to Reproduce
1. Configure cobbler server with self signed certificate
2. Configure terraform cobbler provider ( login/password + url )
3. Add any resource related to cobbler provider
4. `terraform apply`

**Comment by jtopjian** [comment]
@mludy @zulkarnainsncr I have opened #11 which should resolve both SSL-related problems which you've reported.

To use the new support, you would use one or both of the options:

```hcl
provider "cobbler" {
  insecure = true
  cacert_file = "/path/to/ca.crt"
}
```

Unfortunately I do not have a Cobbler environment which I can accurately test this PR with, so if you are able to compile the provider with the patch and test it, I would very much appreciate it!

**Comment by zulkarnainsncr** [comment]
Getting the below compilation error:

echo $PATH

/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/sbin:/Users/zkag0001/.k/runtimes/kre-mono.1.0.0-beta3/bin:/opt/chefdk/bin:/Users/zkag0001/.chefdk/gem/ruby/2.1.0/bin:/opt/chefdk/embedded/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Users/zkag0001/work/bin:/Users/zkag0001/packer:/Users/zkag0001/Downloads/Qemu64bit-OSX-11022017:/Users/zkag0001/dcos/bin:/Users/zkag0001/dcos/dcos/bin:/Users/zkag0001/dcos/apps/dcos/bin

zkagalwallamac:terraform-provider-cobbler zkag0001$ export
PATH=$PATH:$GOPATH/bin

zkagalwallamac:terraform-provider-cobbler zkag0001$ echo $PATH

/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/sbin:/Users/zkag0001/.k/runtimes/kre-mono.1.0.0-beta3/bin:/opt/chefdk/bin:/Users/zkag0001/.chefdk/gem/ruby/2.1.0/bin:/opt/chefdk/embedded/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Users/zkag0001/work/bin:/Users/zkag0001/packer:/Users/zkag0001/Downloads/Qemu64bit-OSX-11022017:/Users/zkag0001/dcos/bin:/Users/zkag0001/dcos/dcos/bin:/Users/zkag0001/dcos/apps/dcos/bin:/Users/zkag0001/work/bin

zkagalwallamac:terraform-provider-cobbler zkag0001$ make build

==> Checking that code complies with gofmt requirements...

go install

main.go:5:2: cannot find package "
github.com/terraform-providers/terraform-provider-cobbler/cobbler" in any
of:

/Users/zkag0001/work/src/
github.com/hashicorp/terraform-provider-cobbler/vendor/github.com/terraform-providers/terraform-provider-cobbler/cobbler
(vendor tree)

/usr/local/go/src/
github.com/terraform-providers/terraform-provider-cobbler/cobbler (from
$GOROOT)

/Users/zkag0001/work/src/
github.com/terraform-providers/terraform-provider-cobbler/cobbler (from
$GOPATH)

make: *** [build] Error 1

zkagalwallamac:terraform-provider-cobbler zkag0001$ pwd

/Users/zkag0001/work/src/github.com/hashicorp/terraform-provider-cobbler

zkagalwallamac:terraform-provider-cobbler zkag0001$ go version

go version go1.9.2 darwin/amd64

zkagalwallamac:terraform-provider-cobbler zkag0001$

**Comment by jtopjian** [comment]
@mludy Thank you for testing this out. 

Can you try the following steps?

```shell
$ go get github.com/terraform-providers/terraform-provider-cobbler
$ cd ~/go/src/github.com/terraform-providers/terraform-provider-cobbler
$ git remote add jtopjian https://github.com/jtopjian/terraform-provider-cobbler
$ git fetch jtopjian
$ git checkout jtopjian/ssl-support
$ make build
```

Let me know if that doesn't work as that was just from memory.

**Comment by zulkarnainsncr** [comment]
I was able to compile.

I copied the cobbler provider to my .terraform directory. I get the below
error.

terraform plan

*Refreshing Terraform state in-memory prior to plan...*

The refreshed state will be used to calculate this plan, but will not be

persisted to local or remote state storage.



------------------------------------------------------------------------


*Error: **Error running plan: 1 error(s) occurred:*


** provider.cobbler: XML syntax error on line 22: element <meta> closed by
</head>*



zkagalwallamac:cobbler zkag0001$ terraform version

Terraform v0.11.2

+ provider.cobbler (unversioned)

**Comment by jtopjian** [comment]
@mludy (oops, I meant @zulkarnainsncr) Thanks for trying this out.

Did you add the `insecure` option to the `provider` block?

**Comment by zulkarnainsncr** [comment]
Yes I did

**Comment by jtopjian** [comment]
@zulkarnainsncr Apologies for directing responses to the wrong person earlier. It looks like you are still getting the same error as you reported in #9? I really have no idea why that's happening.

I set up a test Cobbler environment with a self-signed certificate and verified #11 is working as it should, both with `insecure` and `cacert_file`. So that validates the PR.

We can discuss your issue further in #9 since it looks like it might not be SSL related at all.

**Comment by Xat59** [comment]
Hi guys,

I really need the 'insecure' option !

Thank guys !

**Comment by jtopjian** [comment]
@Xat59 #11 adds support for this. Would you be able to test it out?

**Comment by jtopjian** [comment]
#11 has been merged. Please let me know if anyone still has problems with this.
